### ISSUE TITLE
ZParser's add

### ISSUE THREAD

**Issue by th-ht-zaw** [ofrank123/Zarodenk_Lisp#2]
I can't seem to make this recursive, or at least think of how to approach this recursively. Some of this is due to the different in AbstractSyntaxTree's add method and ZParser's add method. AST will just add the Node into the ArrayList but ZParser has to check for the deepest level of the tree to add a new Node. It's checking for the deepest area where I have the most trouble in (possibly because I'm still figuring out how ArrayLists within ArrayLists work)

**Comment by ofrank123** [comment]
should be done
